## NumPy란?
NumPy는 Python에서 과학 연산을 위한 가장 기본적인 패키지 중 하나입니다. NumPy는 "Numeric Python"의 약자이며 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수와 메소드를 제공합니다. NumPy는 데이터 분석, 데이터 처리, 선형 대수, 머신 러닝 등 다양한 분야에서 널리 사용되고 있습니다.

NumPy의 설치
NumPy를 사용하기 위해서는 먼저 NumPy 패키지를 설치해야 합니다. 아래의 명령어를 사용하여 NumPy를 설치할 수 있습니다.

pip install numpy
NumPy 배열 생성
NumPy에서 가장 기본적인 데이터 구조는 배열입니다. NumPy 배열은 동일한 타입의 데이터를 담는 다차원 배열입니다. NumPy 배열은 ndarray 클래스를 사용하여 생성할 수 있습니다. NumPy 배열을 생성하는 방법은 다음과 같습니다.

# * numpy 란?
- Numerical Python 과학적, 산업적 연산을 위한 파이썬 패키지
- 다차원 배열, 행렬 연산에 주로 사용

- 1차원이 모이면 2차원이 되고
- 2차원이 모이면 3차원이 되고
- 3차원이 모이면 4차원이 되고
- 4차원이 모이면 5차원이 되고 

In [1]:
# !pip install numpy
# !conda install numpy

## * 차원? 
- 0차원 = 점 하나 , 스칼라 
- 1차원 = 선, 벡터([1,2,3,4,5]), 벡터는 방향을 가진 데이터
- 2차원 = 면 
- 3차원 = 공간, 입체
- 다차원 = 3차원 요소가 2개 이상

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [6]:
b = 32

In [12]:
a.ndim

# 출력 : 1
# 뜻 : 1차원 데이터라는 뜻

1

In [7]:
b.ndim

AttributeError: 'int' object has no attribute 'ndim'

In [9]:
c = np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
c

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [13]:
c.ndim

# 출력 : 3 
# 뜻 : 3차원 데이터라는 뜻

3

In [18]:
c.shape

# 2 행 5 열 짜리가 2개 있는 것 : 그래서 3차원이다. 
# 오른쪽 끝에 두자리가 매트릭스다. 행렬
# 차원이 증가하면 앞이 증가한다. 

(2, 2, 5)

In [20]:
d = np.array([[[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]]])
d

array([[[[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]]]])

In [22]:
d.ndim

# 출력 : 4
# 뜻 : 4차원 데이터라는 뜻

4

In [24]:
d.shape

# 2행 5열짜리가 3개 있음

(1, 3, 2, 5)

## * numpy 를 사용하는 이유 : 행렬 연산이 쉽고 빠르기 때문

In [25]:
a = 10

In [26]:
scalar = a + 1 
scalar

11

## 벡터 연산

In [27]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [32]:
c = [5,6,7,8,9]

In [36]:
hap = []
temp = 0

for num in c:
    hap.append(num + 3) 
hap


# 반복문이 필수임
# 행렬에 +3 을 더하는 것임

[8, 9, 10, 11, 12]

## 2차원 연산

In [55]:
# 방법 1
# 매우 귀찮은 방법

d1 = [[1,2,3],[1,2,3],[1,2,3]]
d1

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [56]:
d + 5

# 이렇게 계산이 안됨

TypeError: can only concatenate list (not "int") to list

In [57]:
for i in d:
    for j in i:
        print(j)

1
2
3
1
2
3
1
2
3


In [58]:
for i in d:
    for j in i:
        print(j+5)

6
7
8
6
7
8
6
7
8


In [59]:
hap = []

for i in d:
    temp = []
    for j in i:
        temp.append(j+5)
    hap.append(temp)
hap

[[6, 7, 8], [6, 7, 8], [6, 7, 8]]

In [60]:
# 방법 2
# numpy 를 이용하면 행렬 연산이 쉽고 간편하게 할 수 있다. 

d2 = np.array([[1,2,3],[1,2,3],[1,2,3]])
d2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [61]:
d2 + 5 

array([[6, 7, 8],
       [6, 7, 8],
       [6, 7, 8]])

# numpy 에서 자주 사용하는 메서드 

- .ndim : 몇 차원인지 보는 것
- .shape : 몇 차원, 몇 행 몇 열로 되어있는지 구조 확인
- .size : 배열 안에 있는 요소의 총 갯수가 몇개인지
- .dtype : 데이터 타입이 무엇인지
- .itemsize : 1개 자료의 크기는 몇 인지 

In [62]:
d2.shape

(3, 3)

In [63]:
d2.dtype

dtype('int64')

In [64]:
d2.itemsize

8

In [66]:
d3 = d2 / 2
d3

# 파이썬은 나누기 하면 int 에서 float 으로 datatype이 바뀜

array([[0.5, 1. , 1.5],
       [0.5, 1. , 1.5],
       [0.5, 1. , 1.5]])

In [67]:
d3.dtype

dtype('float64')

## -------------------------------------------------------------------------------------------

# ndarray 만들기
- np.array(리스트/튜플)  : 무조건 리스트나 튜플로 넣어야 함!
- 자료형은 반드시 1가지만 넣는다. <br><br>
1, 2, 3, 4, 5    --> 같은 자료형 int   <br>
1, 2, 3, 4.7, 5     --> 4.7 은 float  <br>
1, '2', 3, 4.8, 5    --> '2'는 문자열str, 4.8은 float, 나머지는 int 이면 다 str 문자열로 통일됨 
<br><br>
* 전체 데이터 형태가 변할 수 있음

In [68]:
np.array(1,2,3,4,5)

# 에러남

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [73]:
e1 = np.array([1,2,3,4,5])
e1

array([1, 2, 3, 4, 5])

In [74]:
e2 = np.array([1,2,3,4,5.3])
e2

# 마지막에 5.3 을 넣었음. 

array([1. , 2. , 3. , 4. , 5.3])

In [75]:
e1.dtype

dtype('int64')

In [76]:
e2.dtype

dtype('float64')

In [79]:
e3 = np.array([1,2, '3', 4, 5.3])
e3

# 문자열str 과 float, int 가 섞여있음
# 문자열이 되어버림

array(['1', '2', '3', '4', '5.3'], dtype='<U32')

In [80]:
e3.dtype

# U32 = 문자열이라는 뜻?

dtype('<U32')

In [82]:
for i in e3:
    print(type(i))
    
    
# numpy.str_ : 문자열

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## np.arange(시작, 끝+1, step) 

In [83]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [85]:
np.arange(1,101,3)

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [86]:
np.arange(3,101,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

## reshape(행, 열) 
* 벡터를 원하는 크기의 matrix로 변환 , 차원도 바꿀 수 있음 

In [87]:
a = np.arange(24)
print(a)
print(a.ndim)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
(24,)


In [88]:
b = a.reshape(3,8)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [89]:
c = a.reshape(8,3)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [91]:
d = a.reshape(3,2,2,2)
d

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [94]:
e = a.reshape(24, )
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [95]:
print(e.ndim)
print(e.shape)

1
(24,)


## flatten( ) : 다차원 데이터를 1차원 배열로 바꿔주는 함수 

In [96]:
d = a.reshape(3,2,2,2)
d

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [100]:
d.flatten()

# 다차원을 1차원 배열로 펼치기
# 괄호가 있음

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## .flip( ) : 행렬의 순서를 뒤집을 때

In [101]:
d

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [102]:
d[::-1]

array([[[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]]])

In [103]:
np.flip(d)

array([[[[23, 22],
         [21, 20]],

        [[19, 18],
         [17, 16]]],


       [[[15, 14],
         [13, 12]],

        [[11, 10],
         [ 9,  8]]],


       [[[ 7,  6],
         [ 5,  4]],

        [[ 3,  2],
         [ 1,  0]]]])

## 정해진 숫자 범위 내에서 균등하게 구간을 나눌 때

* np.linspace(시작, 끝, 구간 수)

In [104]:
np.linspace(0, 1, 123)

array([0.        , 0.00819672, 0.01639344, 0.02459016, 0.03278689,
       0.04098361, 0.04918033, 0.05737705, 0.06557377, 0.07377049,
       0.08196721, 0.09016393, 0.09836066, 0.10655738, 0.1147541 ,
       0.12295082, 0.13114754, 0.13934426, 0.14754098, 0.1557377 ,
       0.16393443, 0.17213115, 0.18032787, 0.18852459, 0.19672131,
       0.20491803, 0.21311475, 0.22131148, 0.2295082 , 0.23770492,
       0.24590164, 0.25409836, 0.26229508, 0.2704918 , 0.27868852,
       0.28688525, 0.29508197, 0.30327869, 0.31147541, 0.31967213,
       0.32786885, 0.33606557, 0.3442623 , 0.35245902, 0.36065574,
       0.36885246, 0.37704918, 0.3852459 , 0.39344262, 0.40163934,
       0.40983607, 0.41803279, 0.42622951, 0.43442623, 0.44262295,
       0.45081967, 0.45901639, 0.46721311, 0.47540984, 0.48360656,
       0.49180328, 0.5       , 0.50819672, 0.51639344, 0.52459016,
       0.53278689, 0.54098361, 0.54918033, 0.55737705, 0.56557377,
       0.57377049, 0.58196721, 0.59016393, 0.59836066, 0.60655

In [106]:
f = np.array([5, 7, 11, 1, 3, 2, 54, 0.5, 0.8])
f

# 정렬이 되어있지 않음

array([ 5. ,  7. , 11. ,  1. ,  3. ,  2. , 54. ,  0.5,  0.8])

In [111]:
f.sort()

# 바로 저장되는거 
# 리스크 있다.

In [110]:
sorted(f)

# 바로 저장되지 않음. 그래서 이거 사용하는게 나음

[np.float64(0.5),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(7.0),
 np.float64(11.0),
 np.float64(54.0)]

In [109]:
f

array([ 0.5,  0.8,  1. ,  2. ,  3. ,  5. ,  7. , 11. , 54. ])

## argsort( ) : 자료 중 값이 작은 것에서 큰 순으로 인덱스 출력 

In [113]:
g = np.array([5, 0.5, -7, 42, 10])
g

array([ 5. ,  0.5, -7. , 42. , 10. ])

In [117]:
g.argsort()

# 인덱스로 출력되는 것임 
# 0 : 가장 작은 -7
# 1 : 두번째로 작은 0.5 

array([2, 1, 0, 4, 3])

## * 배열합치기 
np.concatenate((a, b))

In [164]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(a.shape)   # 행렬 모양이 2행 2열이다 
print()
print(b)
print(b.shape)   # 행렬 모양이 2행 2열이다 

[[1 2]
 [3 4]]
(2, 2)

[[5 6]
 [7 8]]
(2, 2)


* np.concatenate((a,b)) 의 기본 병합 방향은 행방향, axis = 0 
* 행방향으로 합칠 때는 두 행렬의 열의 길이가 같아야 합쳐짐 

In [141]:
concat_row = np.concatenate((a, b))
concat_row

# 기본 병합 방향 : 행방향, axis = 0 이 생략됨

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [142]:
concat_row.shape

# 4행 2열

(4, 2)

* axis = 0   : 행방향으로 붙음
* axis = 1   : 열방향으로 붙음
* 두 행렬의 행 길이가 같아야 붙음

In [143]:
concat_col = np.concatenate((a, b), axis=1)
concat_col

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [144]:
concat_col.shape

# 2행 4열

(2, 4)

## 합치는 방향의 모양이 일치하지 않으면 합치기 X

In [163]:
c = np.array([[1,2],[3,4]])
d = np.array([[5,6]])
print(c)
print(c.shape)   # 행렬 모양이 2행 2열이다 
print(c.ndim)
print()
print(d)
print(d.shape)   # 행렬 모양이 1행 2열이다 
print(d.ndim)

[[1 2]
 [3 4]]
(2, 2)
2

[[5 6]]
(1, 2)
2


In [145]:
concat_row2 = np.concatenate((c, d), axis=0)
concat_row2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [147]:
concat_row2.shape

# 3행 2열

(3, 2)

In [159]:
concat_col2 = np.concatenate((c, d), axis=1)
print(concat_col2.shape)
print(concat_col2)


# 에러가 뜸 
# 반드시 정확하게 shape 이 일치해야 하는데, 일치하지 않아서 합쳐지지 않음 

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [162]:
e = np.array([[1,2],[3,4]])
f = np.array([5,6])
print(e)
print(e.shape)   # 행렬 모양이 2행 2열이다 
print(e.ndim)
print()
print(f)
print(f.shape)   # 벡터
print(f.ndim)

[[1 2]
 [3 4]]
(2, 2)
2

[5 6]
(2,)
1


## vector 와 matrix 는 합칠 수 없다. 

In [154]:
concat_row3 = np.concatenate((e, f), axis=0)
print(concat_row3)
print(concat_row3.shape)

# 에러뜸 
# 반드시 차원이 맞아야 한다. 같은 차원! 
# 벡터와 matrix는 합칠 수 없다. 

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [174]:
concat_col3 = np.concatenate((e, f), axis=1)
print(concat_col3)
print(concat_col3.shape)

# 에러뜸 
# 반드시 차원이 맞아야 한다. 같은 차원! 
# 벡터와 matrix는 합칠 수 없다. 

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [175]:
concat_col2 = np.concatenate((c, d.T), axis=1)
print(concat_col2.shape)
print()
print(concat_col2)

# 아까 위에서는 오류 뜸
# 전치행렬로 만들면 합쳐질 수 있다. 

(2, 3)

[[1 2 5]
 [3 4 6]]


In [176]:
g = np.array([[1,2],[3,4]])
h = np.array([5,6,7])
print(g)
print(g.shape)   # 행렬 모양이 2행 2열이다 
print(g.ndim)
print()
print(h)
print(h.shape)   # 1행 3열의 matrix
print(h.ndim)

[[1 2]
 [3 4]]
(2, 2)
2

[5 6 7]
(3,)
1


In [177]:
concat_col4 = np.concatenate((g, h), axis=1)
print(concat_col4.shape)
print()
print(concat_col4)

# 에러뜸 
# 행렬의 형태가 붙일 수 없기 때문에 안됨

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [178]:
concat_row4 = np.concatenate((g, h), axis=0)
print(concat_row4)
print(concat_row4.shape)

# 에러뜸 
# 행렬의 형태가 같아야 하는데, 같지 않아서 붙일 수 없음 

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

# 전치행렬 만들기 
* .T
* .transpose()
* .reshape()

In [179]:
h

array([5, 6, 7])

In [180]:
print(h)
print(h.shape)

[5 6 7]
(3,)


In [181]:
h2 = h.T
print(h2)
print(h2.shape)

[5 6 7]
(3,)


In [182]:
h3 = h.transpose()
print(h3)
print(h3.shape)

[5 6 7]
(3,)


In [ ]:
# trnanspose 나 .T 를 더 사용하기 